frameworkVersion: '3'
service: fleur-fragrances-api

provider:
  name: aws
  runtime: python3.11
  stage: ${opt:stage, 'prod'}
  region: ${opt:region, 'ap-south-1'}
  timeout: 30
  memorySize: 512
  environment:
    MONGO_URL: mongodb+srv://nivedhappu042_db_user:JvjBUdaHykzj7CHZ@cluster0.m9yue03.mongodb.net/?appName=Cluster0
    DB_NAME: fleur_fragrances
    JWT_SECRET: fleur_fragrances_secret_key_2025
    CORS_ORIGINS: '*'

functions:
  api:
    handler: handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    slim: true
    strip: false
    slimPatternsAppendDefaults: true
    slimPatterns:
      - '**/*.egg-info*'
      - '**/*.dist-info*'
      - '**/__pycache__*'
      - '**/tests/**'
      - '**/test/**'

package:
  patterns:
    - '!.env'
    - '!tests/**'
    - '!__pycache__/**'
    - '!.pytest_cache/**'
    - '!node_modules/**'
